### ISSUE TITLE
Uiza android player sdk integration

### ISSUE THREAD

**Issue by datnt1987** [uizaio/uiza-android-player-sdk#1]
Dear uiza team,

I've integrated uiza android sdk into my project (using kotlin) with fragment, but build failed with "cannot access UZPlayback" error. The code is below:

  override fun setupUI() {
        super.setupUI()
        uzvStreamingView.setUZCallback(this)
        uzvStreamingView.setAutoMoveToLiveEdge(true)
        onPlay("streaming play back url)
    }

    private fun onPlay(playBackUrl: String?) {
        playBackUrl?.let {
            UZPlayback().apply {
                hls = it
                isLive = false
                val isInitSuccess: Boolean = uzvStreamingView.play(this)
                if (!isInitSuccess) {
                    Timber.d("Init failed")
                }
            }
        }
    }

Please check my error and let me know my wrong integration

**Comment by neilndev** [comment]
Hi @datnt1987,
My source code:

```
playBackUrl?.let {
            val playback = UZPlayback().apply {
                hls = it
                isLive = false
            }
            val isInitSuccess: Boolean = uzVideoView.play(playback)
            if (!isInitSuccess) {
                Timber.d("Init failed")
            }
        }
```
And it works fine.

**Comment by datnt1987** [comment]
Dear @namndev ,

I retried and found that I miss implementing in other gradle. The code now works fine and thanks so much for supporting me soon as you can, thanks team as well
